### PR TITLE
fixes the crash while building the APK

### PR DESCRIPTION
**Pull request by daadu**
Android Resources of 25 compile SDK does not match with that of 28

```
1: Task failed with an exception.                                       
-----------                                                             
* What went wrong:                                                      
Execution failed for task ':qrcode_reader:verifyReleaseResources'.      
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /home/harsh/.gradle/caches/transforms-2/files-2.1/79a43a903ecb6dc82204ee669e724ddc/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontStyle not found.
                                                                        
     /home/harsh/.gradle/caches/transforms-2/files-2.1/79a43a903ecb6dc82204ee669e724ddc/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/font not found.
                                                                        
     /home/harsh/.gradle/caches/transforms-2/files-2.1/79a43a903ecb6dc82204ee669e724ddc/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontWeight not found.
                                                                        
     /home/harsh/.gradle/caches/transforms-2/files-2.1/79a43a903ecb6dc82204ee669e724ddc/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
     /home/harsh/.gradle/caches/transforms-2/files-2.1/79a43a903ecb6dc82204ee669e724ddc/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

```

### CODE REVIEW

**Comment by atiqsamtia** [comment]
Ah! Thanks, Man! you are a life savior.  I was searching for the solution for this from a few weeks.

Please push the update to pub.dev as well. I'm currently using it via git in pubspec

**Comment by peterlauri** [comment]
@daadu this is not yet included in the pub.dev release, right? I'm facing the same problem...

**Comment by atiqsamtia** [comment]
@peterlauri this is not updated on pub.dev yet. Use it via GitHub like this in pubspec.yaml
```
  qrcode_reader:
    git: https://github.com/bcko/flutter_qrcode_reader.git
```

I'm using like this and it is working fine

**Comment by johanhenselmans** [comment]
Did you use the git repository? Unfortunately I am not able to publish the git version on pub.dev

**Pull request merged**
